export const sliderData = [
  {
    title: "BAKAYISHONGA Emma",
    image: require("../assets/images/homescreen/bakayishonga.jpg"),
    artist: "DUSABE King Christian",
  },
  {
    title: "The Guitarist",
    image: require("../assets/images/homescreen/the-guitarist.jpg"),
    artist: "HABIYAREMYE Dieu Donne",
  },
  {
    title: "Past Pain",
    image: require("../assets/images/homescreen/past-pain.jpg"),
    artist: "NIYOMUGABO Benjamin",
  },
  {
    title: "Untitled",
    image: require("../assets/images/gallery/paid/untitled-1.png"),
    artist: "DUSABE King Christian",
  },
  {
    title: "Friday",
    image: require("../assets/images/gallery/friday.jpg"),
    artist: "TUYISHIME Benjamin",
  },
  {
    title: "The Disguise",
    image: require("../assets/images/gallery/the-disguise.jpg"),
    artist: "KATUREBE Beni Noel",
  },
];

export const freeArt = [
  {
    poster: require("../assets/images/gallery/the-disguise.jpg"),
    title: "The Disguise",
    subtitle: "Digital Illustration",
    isFree: "Yes",
    price: "25.99",
    id: "1",
    artist: "KATUREBE Beni Noel",
  },
  {
    poster: require("../assets/images/gallery/shine.jpg"),
    title: "Shine",
    subtitle: "Digital Illustration",
    isFree: "Yes",
    price: "25.99",
    id: "2",
    artist: "KATUREBE Beni Noel",
  },
  {
    poster: require("../assets/images/gallery/friday.jpg"),
    title: "Friday",
    subtitle: "Digital Illustration",
    isFree: "Yes",
    price: "29.99",
    id: "3",
    artist: "TUYISHIME Benjamin",
  },
];
export const paidArt = [
  {
    poster: require("../assets/images/gallery/paid/devotion.jpg"),
    title: "Devotion",
    subtitle: "Painting",
    isFree: "No",
    price: "1,499.99",
    id: "1",
    artist: "IZERE Antoine",
    description: "",
  },
  {
    poster: require("../assets/images/gallery/paid/embrace.jpg"),
    title: "Embrace",
    subtitle: "Painting",
    isFree: "No",
    price: "1,499.99",
    id: "2",
    artist: "DUSABE King Christian",
  },
  {
    poster: require("../assets/images/gallery/paid/visage.jpg"),
    title: "Visage",
    subtitle: "Painting",
    isFree: "No",
    price: "1,499.99",
    id: "3",
    artist: "IZERE Antoine",
  },
  {
    poster: require("../assets/images/gallery/paid/mother.jpeg"),
    title: "Mother",
    subtitle: "Painting",
    isFree: "No",
    price: 1399.99,
    id: "4",
    artist: "DUSABE King Christian",
  },
  {
    poster: require("../assets/images/gallery/paid/visage-2.jpg"),
    title: "Visage",
    subtitle: "Painting",
    isFree: "No",
    price: "1,499.99",
    id: "5",
    artist: "IZERE Antoine",
  },
  {
    poster: require("../assets/images/gallery/paid/untitled.jpg"),
    title: "Untitled",
    subtitle: "Painting",
    isFree: "No",
    price: "1,499.99",
    id: "6",
    artist: "DUSABE King Christian",
  },
];
